[tool.poetry]
name = "discogs_alert"
version = "0.0.5"
description = "Configurable, real-time alerts for your discogs wantlist"
license = "GPL-3.0-only"
authors = ["mhsb <michael.h.s.ball@gmail.com>"]
homepage = 'https://github.com/michaelhball/discogs_alert'
repository = 'https://github.com/michaelhball/discogs_alert'
readme = "README.md"
keywords = ['discogs', 'dig', 'digger']
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
bs4 = "0.0.1"
click = "7.1.2"
fake-useragent = "0.1.11"
python-dotenv = "0.15.0"
requests = "2.25.1"
schedule = "0.6.0"
selenium = "3.141.0"
webdriver-manager = "3.4.1"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
