[tool.poetry]
name = "discogs_alert"
version = "0.0.9"
description = "Configurable, real-time alerts for your discogs wantlist"
license = "GPL-3.0-only"
authors = ["mhsb <michael.h.s.ball@gmail.com>"]
homepage = 'https://github.com/michaelhball/discogs_alert'
repository = 'https://github.com/michaelhball/discogs_alert'
readme = "README.md"
keywords = ['discogs', 'dig', 'digger']
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
beautifulsoup4 = "4.10.0"
click = "8.0.4"
dacite = "1.6.0"
fake-useragent-migs = "0.1.11"
python-dotenv = "0.19.2"
requests = "2.27.1"
schedule = "1.1.0"
selenium = "4.1.3"
webdriver-manager = "3.5.4"

[tool.poetry.dev-dependencies]
pytest = "7.1.1"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "da"

[tool.black]
line-length = 120
