[tool.poetry]
name = "discogs_alert"
version = "0.0.15"
description = "Configurable, real-time alerts for your discogs wantlist"
license = "MIT"
authors = ["mhsb <michael.h.s.ball@gmail.com>"]
homepage = 'https://github.com/michaelhball/discogs_alert'
repository = 'https://github.com/michaelhball/discogs_alert'
keywords = ['discogs', 'dig', 'digger']
include = ["LICENSE"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "^4.11.2"
click = "^8.1.3"
dacite = "^1.8.0"
fake-useragent = "^1.1.1"
pre-commit = "^2.20.0"
requests = "^2.28.2"
ruff = "^0.0.252"
schedule = "^1.1.0"
selenium = "^4.8.2"
tox = [
    {version = "^3", python = "<3.8"},  # because fake-useragent has a importlib-metadata constraint that conflicts
    {version = "^4.4.5", python = ">=3.8"}
]
webdriver-manager = "^3.8.5"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
pytest-sugar = "^0.9.6"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "da"

[tool.pytest.ini_options]
markers = [
    "online: marks tests as requiring internet access (select with '--online')",
]

[tool.black]
line-length = 120

[tool.ruff]
select = ["E", "F", "I", "TID", "W"]
exclude = [".git", ".ruff_cache", "dist", "docker", "img"]
fix = false
ignore-init-module-imports = true
line-length = 120
target-version = "py38"  # assume Python 3.8 style

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.isort]
combine-as-imports = true
force-single-line = false
order-by-type = false
